
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package JflexyCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLIZQUIERDA = 27;
  public static final int PYCOMA = 23;
  public static final int DECIMAL = 32;
  public static final int SUM = 16;
  public static final int ETIQUETAS = 8;
  public static final int EJECUTAR = 21;
  public static final int PIZQUIERDA = 22;
  public static final int TIPO = 11;
  public static final int PORCENTAJE = 15;
  public static final int BARRAS = 3;
  public static final int VALORES = 9;
  public static final int COMA = 24;
  public static final int MULT = 18;
  public static final int EOF = 0;
  public static final int TOTAL = 12;
  public static final int DEF = 2;
  public static final int DIV = 19;
  public static final int PIE = 4;
  public static final int EXTRA = 13;
  public static final int CANT = 14;
  public static final int error = 1;
  public static final int PAL = 30;
  public static final int EJEY = 7;
  public static final int EJEX = 6;
  public static final int ENTERO = 31;
  public static final int REST = 17;
  public static final int CDERECHA = 25;
  public static final int UNIR = 10;
  public static final int DPUNTOS = 29;
  public static final int PDERECHA = 20;
  public static final int TITULO = 5;
  public static final int LLDERECHA = 28;
  public static final int CIZQUIERDA = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "CANT",
  "PORCENTAJE",
  "SUM",
  "REST",
  "MULT",
  "DIV",
  "PDERECHA",
  "EJECUTAR",
  "PIZQUIERDA",
  "PYCOMA",
  "COMA",
  "CDERECHA",
  "CIZQUIERDA",
  "LLIZQUIERDA",
  "LLDERECHA",
  "DPUNTOS",
  "PAL",
  "ENTERO",
  "DECIMAL"
  };
}

